import type { Metadata } from "next";
import type { ReactNode } from "react";

import Container from "@/components/container";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const OpenTicketLayout = ({ children }: { children: ReactNode }) => {
  return <Container>{children}</Container>;
};

export default OpenTicketLayout;
